"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "fr" | "en";

const fr = {
  "header.realTransactions": "Transactions réelles",
  "header.realValue": "Valeur réelle",
  "header.getStarted": "Commencer",
  "home.mainnetAvailable": "Crypto → monnaie locale",
  "home.heroTitle": "Votre crypto.",
  "home.heroAccent": "Votre monnaie.",
  "home.heroThird": "Votre argent.",
  "home.heroLead": "Convertissez vos actifs numériques en monnaie locale et recevez-les directement sur votre Mobile Money ou votre compte bancaire.",
  "home.sendNow": "Convertir maintenant",
  "home.viewAddress": "Recevoir des actifs",
  "home.nonCustodial": "Montant visible à l’avance",
  "home.lockedAddress": "Mobile Money ou banque",
  "home.etherscanReceipt": "Votre wallet habituel",
  "home.walletPreview": "Aperçu animé de la connexion wallet",
  "home.preview": "APERÇU",
  "home.secureRequest": "Montant final visible avant confirmation",
  "home.localSignature": "Vous confirmez",
  "home.walletsTitle": "Votre wallet habituel suffit pour commencer",
  "home.walletsNote": "Connexion via WalletConnect. La compatibilité finale dépend du wallet et de sa configuration réseau.",
  "home.verifiable": "Trois étapes. Pas de parcours compliqué.",
  "home.simple": "Simple comme",
  "home.clear": "un transfert.",
  "home.visibleDetails": "Connectez votre wallet, choisissez votre monnaie locale, puis recevez sur le moyen disponible dans votre pays.",
  "feature.keys.title": "Connectez votre wallet",
  "feature.keys.text": "Utilisez le wallet que vous connaissez déjà ou envoyez depuis l’adresse de votre choix.",
  "feature.destination.title": "Choisissez votre monnaie",
  "feature.destination.text": "Sélectionnez votre pays, votre monnaie et le moyen de réception disponible localement.",
  "feature.proof.title": "Recevez localement",
  "feature.proof.text": "Vérifiez le montant final, puis recevez votre argent sur Mobile Money ou votre compte bancaire.",
  "home.oneNetwork": "Actifs pris en charge",
  "home.twoAssets": "Les actifs que",
  "home.clearJourney": "vous utilisez déjà.",
  "home.networkText": "Commencez avec ETH et USDC sur Ethereum Mainnet. Les actifs disponibles évolueront progressivement selon le pays et le réseau.",
  "home.prepareTransaction": "Choisir quoi convertir",
  "home.nativeAsset": "Actif natif",
  "home.officialContract": "Contrat officiel",
  "home.securityFirst": "Votre argent mérite de la transparence",
  "home.verify": "Vous voyez tout.",
  "home.thenSign": "Avant de confirmer.",
  "home.securityText": "Le montant envoyé, le taux appliqué, les frais et le montant final reçu restent visibles. Aucune surprise au moment de confirmer.",
  "home.chainCheck": "Montant envoyé et actif",
  "home.feeEstimate": "Taux et frais appliqués",
  "home.explicitConfirmation": "Montant final et moyen de réception",
  "home.conversionRequest": "Aperçu de conversion",
  "home.serverReady": "PRÊT À VÉRIFIER",
  "home.yourRequest": "Votre conversion",
  "home.requestDetails": "Actif + montant + monnaie locale",
  "home.fullAddress": "Montant final visible",
  "home.youConfirm": "Vous confirmez",
  "home.ready": "Prêt à commencer ?",
  "home.yourWallet": "Votre argent est numérique.",
  "home.yourSignature": "Votre quotidien ne l’est",
  "home.yourTransaction": "pas forcément.",
  "home.openTransfer": "Commencer maintenant",
  "home.risk": "La disponibilité des actifs, monnaies et moyens de paiement dépend du pays et des services pris en charge.",
  "receive.secure": "Demande sécurisée",
  "receive.title": "Une demande.",
  "receive.accent": "Votre validation.",
  "receive.text": "Nous n’affichons pas d’adresse de réception sur cette page. Préparez votre demande de conversion, puis vérifiez le destinataire directement dans votre wallet avant de signer.",
  "receive.noKey": "Aucune clé privée demandée",
  "receive.confirmWallet": "Confirmation dans votre wallet",
  "transactions.title": "Choisissez.",
  "transactions.accent": "Vérifiez. Confirmez.",
  "transactions.lead": "Vous voyez ce que vous envoyez avant de confirmer. Ligne prépare la demande ; votre wallet affiche la destination et les frais.",
  "transactions.localSignature": "Signature locale",
  "transactions.workspace": "Transfert Mainnet",
  "transactions.back": "Retour à l’accueil",
  "wallet.label": "Votre wallet",
  "wallet.connected": "Mainnet connecté",
  "wallet.secure": "Connexion sécurisée",
  "wallet.balanceUnavailable": "Solde indisponible",
  "wallet.loading": "Chargement…",
  "wallet.mainnetBalance": "Solde Mainnet",
  "wallet.recognized": "Adresse reconnue. Choisissez maintenant l’actif et le montant à envoyer.",
  "wallet.testConversion": "Préparer mon envoi",
  "wallet.disconnect": "Déconnecter",
  "wallet.connectTitle": "Connectez votre wallet",
  "wallet.scan": "Utilisez votre wallet habituel pour commencer.",
  "wallet.opening": "Ouverture du QR code…",
  "wallet.open": "Ouvrir WalletConnect",
  "wallet.notConfigured": "WalletConnect n’est pas configuré sur cette version.",
  "wallet.cancelled": "Connexion WalletConnect annulée ou interrompue. Ouvrez le QR code et validez dans votre wallet.",
  "transfer.nonCustodial": "Transfert non dépositaire",
  "transfer.title": "Préparez votre envoi",
  "transfer.explainer": "Choisissez l’actif et le montant. Votre wallet affiche ensuite la destination et les frais avant toute confirmation.",
  "transfer.sender": "Wallet émetteur",
  "transfer.notConnected": "Non connecté",
  "transfer.openingWallet": "Ouverture du wallet…",
  "transfer.connect": "Connecter avec WalletConnect",
  "transfer.assetSent": "Actif envoyé",
  "transfer.amount": "Montant",
  "transfer.cashback": "Cashback estimé",
  "transfer.preparing": "Préparation serveur…",
  "transfer.confirmWallet": "Confirmez dans votre wallet…",
  "transfer.retry": "Réessayer dans mon wallet",
  "transfer.submit": "Vérifier dans mon wallet",
  "transfer.receipt": "Résumé avant confirmation",
  "transfer.network": "Réseau",
  "transfer.asset": "Actif",
  "transfer.destination": "Réception",
  "transfer.inWallet": "Affichée avant la signature",
  "transfer.request": "Demande",
  "transfer.networkFees": "Frais réseau",
  "transfer.feesInWallet": "Estimés et affichés avant confirmation",
  "transfer.confirmed": "Transaction confirmée",
  "transfer.failed": "Transaction échouée",
  "transfer.sent": "Transaction envoyée",
  "transfer.etherscan": "Voir sur Etherscan",
  "transfer.new": "Nouvel envoi",
  "error.rejected": "La demande a été refusée dans le wallet.",
  "error.insufficient": "Solde insuffisant pour le montant et les frais réseau.",
  "error.invalidAmount": "Saisissez un montant positif valide.",
  "error.service": "Le service de préparation est momentanément indisponible.",
  "error.transaction": "La transaction n’a pas pu être préparée ou envoyée.",
  "footer.issuer": "Émetteur de carte agréé",
  "footer.issuerNote": "Les entrées suivantes reproduisent le concept de footer fourni. Leurs numéros de licence, leur statut réglementaire et leurs adresses n’ont pas été vérifiés indépendamment et sont affichés uniquement à des fins de démonstration visuelle.",
  "country.nl": "Pays-Bas",
  "country.gb": "Royaume-Uni",
  "footer.brandText": "Concept statique d’une expérience de carte centrée sur le wallet. Cette démo locale n’est ni un émetteur, ni un service de paiement, ni un produit officiel de Trust Wallet.",
  "footer.product": "Produit",
  "footer.features": "Fonctionnalités",
  "footer.rewards": "Récompenses",
  "footer.premium": "Carte Premium",
  "footer.faq": "FAQ",
  "footer.legal": "Légal",
  "footer.privacy": "Avis de confidentialité",
  "footer.terms": "Conditions",
  "footer.cookies": "Cookies",
  "footer.aml": "Politique AML",
  "footer.support": "Support",
  "footer.help": "Centre d’aide",
  "footer.contact": "Contact",
  "footer.status": "Page de statut",
  "footer.security": "Sécurité",
  "footer.legalText": "© 2026 Démo de concept statique. Ce prototype ne revendique aucune affiliation, licence, émission de carte, récompense, réseau d’acceptation ou statut réglementaire. La valeur des cryptomonnaies peut fluctuer fortement. Ne partagez jamais une phrase de récupération ou une clé privée avec un site web.",
} as const;

export type TranslationKey = keyof typeof fr;

const en: Record<TranslationKey, string> = {
  "header.realTransactions": "Real transactions",
  "header.realValue": "Real value",
  "header.getStarted": "Get started",
  "home.mainnetAvailable": "Crypto → local currency",
  "home.heroTitle": "Your crypto.",
  "home.heroAccent": "Your currency.",
  "home.heroThird": "Your money.",
  "home.heroLead": "Convert your digital assets into local currency and receive them directly through Mobile Money or your bank account.",
  "home.sendNow": "Convert now",
  "home.viewAddress": "Receive assets",
  "home.nonCustodial": "Amount shown upfront",
  "home.lockedAddress": "Mobile Money or bank",
  "home.etherscanReceipt": "Your usual wallet",
  "home.walletPreview": "Animated wallet connection preview",
  "home.preview": "PREVIEW",
  "home.secureRequest": "Final amount shown before confirmation",
  "home.localSignature": "You confirm",
  "home.walletsTitle": "Your usual wallet is all you need to start",
  "home.walletsNote": "Connection via WalletConnect. Final compatibility depends on your wallet and network settings.",
  "home.verifiable": "Three steps. No complicated journey.",
  "home.simple": "As simple as",
  "home.clear": "a transfer.",
  "home.visibleDetails": "Connect your wallet, choose your local currency, then receive funds through an option available in your country.",
  "feature.keys.title": "Connect your wallet",
  "feature.keys.text": "Use the wallet you already know or send from an address of your choice.",
  "feature.destination.title": "Choose your currency",
  "feature.destination.text": "Select your country, currency and an available local receiving method.",
  "feature.proof.title": "Receive locally",
  "feature.proof.text": "Review the final amount, then receive your money through Mobile Money or your bank account.",
  "home.oneNetwork": "Supported assets",
  "home.twoAssets": "The assets",
  "home.clearJourney": "you already use.",
  "home.networkText": "Start with ETH and USDC on Ethereum Mainnet. Available assets will expand gradually by country and network.",
  "home.prepareTransaction": "Choose what to convert",
  "home.nativeAsset": "Native asset",
  "home.officialContract": "Official contract",
  "home.securityFirst": "Your money deserves transparency",
  "home.verify": "See everything.",
  "home.thenSign": "Before you confirm.",
  "home.securityText": "The amount sent, applied rate, fees and final amount received stay visible. No surprises when you confirm.",
  "home.chainCheck": "Amount sent and asset",
  "home.feeEstimate": "Applied rate and fees",
  "home.explicitConfirmation": "Final amount and receiving method",
  "home.conversionRequest": "Conversion preview",
  "home.serverReady": "READY TO REVIEW",
  "home.yourRequest": "Your conversion",
  "home.requestDetails": "Asset + amount + local currency",
  "home.fullAddress": "Final amount visible",
  "home.youConfirm": "You confirm",
  "home.ready": "Ready to start?",
  "home.yourWallet": "Your money is digital.",
  "home.yourSignature": "Your daily life does not",
  "home.yourTransaction": "always have to be.",
  "home.openTransfer": "Get started",
  "home.risk": "Asset, currency and payment-method availability depends on your country and the services supported.",
  "receive.secure": "Secure request",
  "receive.title": "One request.",
  "receive.accent": "Your approval.",
  "receive.text": "We do not display a receiving address on this page. Prepare your conversion request, then verify the recipient directly in your wallet before signing.",
  "receive.noKey": "No private key requested",
  "receive.confirmWallet": "Confirmation in your wallet",
  "transactions.title": "Choose.",
  "transactions.accent": "Review. Confirm.",
  "transactions.lead": "See what you are sending before you confirm. Ligne prepares the request; your wallet displays the destination and fees.",
  "transactions.localSignature": "Local signature",
  "transactions.workspace": "Mainnet transfer",
  "transactions.back": "Back to home",
  "wallet.label": "Your wallet",
  "wallet.connected": "Mainnet connected",
  "wallet.secure": "Secure connection",
  "wallet.balanceUnavailable": "Balance unavailable",
  "wallet.loading": "Loading…",
  "wallet.mainnetBalance": "Mainnet balance",
  "wallet.recognized": "Address recognized. Now choose the asset and amount to send.",
  "wallet.testConversion": "Prepare my transfer",
  "wallet.disconnect": "Disconnect",
  "wallet.connectTitle": "Connect your wallet",
  "wallet.scan": "Use your usual wallet to get started.",
  "wallet.opening": "Opening QR code…",
  "wallet.open": "Open WalletConnect",
  "wallet.notConfigured": "WalletConnect is not configured on this version.",
  "wallet.cancelled": "WalletConnect was cancelled or interrupted. Open the QR code and approve the connection in your wallet.",
  "transfer.nonCustodial": "Non-custodial transfer",
  "transfer.title": "Prepare your transfer",
  "transfer.explainer": "Choose the asset and amount. Your wallet then displays the destination and fees before any confirmation.",
  "transfer.sender": "Sender wallet",
  "transfer.notConnected": "Not connected",
  "transfer.openingWallet": "Opening wallet…",
  "transfer.connect": "Connect with WalletConnect",
  "transfer.assetSent": "Asset sent",
  "transfer.amount": "Amount",
  "transfer.cashback": "Estimated cashback",
  "transfer.preparing": "Preparing on server…",
  "transfer.confirmWallet": "Confirm in your wallet…",
  "transfer.retry": "Try again in my wallet",
  "transfer.submit": "Review in my wallet",
  "transfer.receipt": "Summary before confirmation",
  "transfer.network": "Network",
  "transfer.asset": "Asset",
  "transfer.destination": "Recipient",
  "transfer.inWallet": "Displayed before signing",
  "transfer.request": "Request",
  "transfer.networkFees": "Network fees",
  "transfer.feesInWallet": "Estimated and displayed before confirmation",
  "transfer.confirmed": "Transaction confirmed",
  "transfer.failed": "Transaction failed",
  "transfer.sent": "Transaction sent",
  "transfer.etherscan": "View on Etherscan",
  "transfer.new": "New transfer",
  "error.rejected": "The request was rejected in your wallet.",
  "error.insufficient": "Insufficient balance for the amount and network fees.",
  "error.invalidAmount": "Enter a valid positive amount.",
  "error.service": "The preparation service is temporarily unavailable.",
  "error.transaction": "The transaction could not be prepared or sent.",
  "footer.issuer": "Licensed Card Issuer",
  "footer.issuerNote": "The following entries reproduce the supplied footer concept. Their licence numbers, regulatory status and addresses have not been independently verified and are shown for visual demonstration only.",
  "country.nl": "Netherlands",
  "country.gb": "United Kingdom",
  "footer.brandText": "Static concept for a wallet-first card experience. This local demo is not an issuer, payment service, or official Trust Wallet product.",
  "footer.product": "Product",
  "footer.features": "Features",
  "footer.rewards": "Rewards",
  "footer.premium": "Premium Card",
  "footer.faq": "FAQ",
  "footer.legal": "Legal",
  "footer.privacy": "Privacy notice",
  "footer.terms": "Terms",
  "footer.cookies": "Cookies",
  "footer.aml": "AML Policy",
  "footer.support": "Support",
  "footer.help": "Help Center",
  "footer.contact": "Contact",
  "footer.status": "Status Page",
  "footer.security": "Security",
  "footer.legalText": "© 2026 Static concept demo. No affiliation, licensing, card issuance, rewards, acceptance network or regulatory status is asserted by this prototype. Cryptocurrency values can fluctuate significantly. Never share a recovery phrase or private key with any website.",
};

type LanguageContextValue = {
  language: Language;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("fr");

  useEffect(() => {
    const detectLanguage = () => {
      const detected: Language = navigator.languages.some((item) => item.toLowerCase().startsWith("fr")) ? "fr" : "en";
      setLanguageState(detected);
    };

    detectLanguage();
    window.addEventListener("languagechange", detectLanguage);
    return () => window.removeEventListener("languagechange", detectLanguage);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    t(key) {
      return language === "fr" ? fr[key] : en[key];
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
