"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "fr" | "en";

const fr = {
  "header.realTransactions": "Transactions réelles",
  "header.realValue": "Valeur réelle",
  "header.getStarted": "Commencer",
  "home.mainnetAvailable": "Crypto → monnaie locale",
  "home.heroTitle": "L’argent numérique,",
  "home.heroAccent": "enfin local.",
  "home.heroLead": "Transformez vos crypto et stablecoins en monnaie locale et recevez votre argent directement sur le moyen de paiement que vous utilisez au quotidien.",
  "home.heroAssets": "ETH, BTC, USDT, USDC et autres actifs pris en charge → XAF, NGN, GHS, ZAR et autres monnaies locales.",
  "home.sendNow": "Convertir maintenant",
  "home.nonCustodial": "Montant visible à l’avance",
  "home.lockedAddress": "Mobile Money ou banque",
  "home.etherscanReceipt": "Votre wallet habituel",
  "home.walletPreview": "Aperçu animé de la connexion wallet",
  "home.preview": "APERÇU",
  "home.secureRequest": "Montant final visible avant confirmation",
  "home.localSignature": "Vous confirmez",
  "home.previewSendLabel": "Vous envoyez",
  "home.previewSendValue": "100 USDT",
  "home.previewReceiveLabel": "Vous recevez",
  "home.previewReceiveValue": "≈ 59 800 XAF",
  "home.previewCountryLabel": "Pays",
  "home.previewCountryValue": "Cameroun",
  "home.previewMethodLabel": "Recevoir sur",
  "home.previewMethodValue": "MTN Mobile Money",
  "home.walletsTitle": "Votre wallet habituel suffit pour commencer",
  "home.walletsNote": "Connexion via WalletConnect. La compatibilité finale dépend du wallet et de sa configuration réseau.",
  "home.countriesKicker": "Disponible dans ces pays avec Mobile Money",
  "home.countriesNote": "La liste des pays et des moyens de réception disponibles s’agrandira progressivement.",
  "home.verifiable": "Trois étapes. Pas de parcours compliqué.",
  "home.simple": "Simple comme",
  "home.clear": "un transfert.",
  "home.visibleDetails": "Connectez votre wallet, choisissez votre monnaie locale, puis recevez sur le moyen disponible dans votre pays.",
  "feature.keys.title": "Connectez votre wallet",
  "feature.keys.text": "Sélectionnez votre wallet ou indiquez l’adresse depuis laquelle vous souhaitez envoyer vos actifs.",
  "feature.destination.title": "Choisissez votre monnaie",
  "feature.destination.text": "Sélectionnez votre pays et la monnaie dans laquelle vous souhaitez recevoir votre argent.",
  "feature.proof.title": "Recevez localement",
  "feature.proof.text": "Nous convertissons et envoyons les fonds vers le moyen de paiement disponible dans votre pays.",
  "home.oneNetwork": "Actifs pris en charge",
  "home.twoAssets": "Les actifs que",
  "home.clearJourney": "vous utilisez déjà.",
  "home.networkText": "Envoyez ETH, USDC et USDT sur Ethereum Mainnet. Le parcours BTC natif est présenté séparément pour rendre le réseau explicite avant toute confirmation.",
  "home.prepareTransaction": "Choisir quoi convertir",
  "home.nativeAsset": "Vous envoyez",
  "home.cryptoAssetsLabel": "Crypto & stablecoins",
  "home.cryptoAssetsList": "ETH · BTC · USDT · USDC",
  "home.chainBadgeTop": "CRYPTO",
  "home.chainBadgeBottom": "LOCAL",
  "home.officialContract": "Vous recevez",
  "home.localCurrenciesLabel": "Monnaies locales",
  "home.localCurrenciesList": "XAF · NGN · GHS · ZAR",
  "home.securityFirst": "Votre argent mérite de la transparence",
  "home.verify": "Vous voyez tout.",
  "home.thenSign": "Avant de confirmer.",
  "home.securityText": "Le montant envoyé, le taux appliqué, les frais et le montant final reçu restent visibles. Aucune surprise au moment de confirmer.",
  "home.chainCheck": "Montant envoyé et actif",
  "home.feeEstimate": "Taux et frais appliqués",
  "home.explicitConfirmation": "Montant final et moyen de réception",
  "home.conversionRequest": "Aperçu de conversion",
  "home.serverReady": "PRÊT À VÉRIFIER",
  "home.yourRequest": "Votre conversion",
  "home.requestDetails": "Actif + montant + monnaie locale",
  "home.fullAddress": "Montant final visible",
  "home.youConfirm": "Vous confirmez",
  "home.ready": "Prêt à commencer ?",
  "home.yourWallet": "Votre argent est numérique.",
  "home.yourSignature": "Votre quotidien ne l’est",
  "home.yourTransaction": "pas forcément.",
  "home.openTransfer": "Commencer maintenant",
  "home.risk": "La disponibilité des actifs, monnaies et moyens de paiement dépend du pays et des services pris en charge.",
  "transactions.title": "Choisissez.",
  "transactions.accent": "Vérifiez. Confirmez.",
  "transactions.lead": "Choisissez BTC, ETH, USDT ou USDC. Ligne affiche le réseau avant que votre wallet ne présente la destination et les frais.",
  "transactions.localSignature": "Signature locale",
  "transactions.workspace": "Transfert Mainnet",
  "transactions.back": "Retour à l’accueil",
  "wallet.label": "Votre wallet",
  "wallet.connected": "Mainnet connecté",
  "wallet.secure": "Connexion sécurisée",
  "wallet.balanceUnavailable": "Solde indisponible",
  "wallet.loading": "Chargement…",
  "wallet.mainnetBalance": "Solde Mainnet",
  "wallet.recognized": "Adresse reconnue. Choisissez maintenant l’actif et le montant à envoyer.",
  "wallet.testConversion": "Préparer mon envoi",
  "wallet.disconnect": "Déconnecter",
  "wallet.connectTitle": "Connectez votre wallet",
  "wallet.scan": "Utilisez votre wallet habituel pour commencer.",
  "wallet.opening": "Ouverture du QR code…",
  "wallet.open": "Ouvrir WalletConnect",
  "wallet.notConfigured": "WalletConnect n’est pas configuré sur cette version.",
  "wallet.cancelled": "Connexion WalletConnect annulée ou interrompue. Ouvrez le QR code et validez dans votre wallet.",
  "transfer.countryPromptTitle": "Où souhaitez-vous recevoir votre argent ?",
  "transfer.countryPromptSubtitle": "Sélectionnez votre pays pour voir les monnaies et moyens de réception disponibles.",
  "transfer.countryPromptHint": "Choisissez un pays pour continuer.",
  "transfer.genericPitchTitle": "Votre crypto, reçue localement.",
  "transfer.genericPitchSubtitle": "Convertissez vos actifs pris en charge et recevez votre argent sur le moyen de réception disponible dans votre pays.",
  "transfer.phonePromptTitle": "Sur quel numéro souhaitez-vous recevoir vos fonds ?",
  "transfer.phonePromptSubtitle": "Cet indicatif correspond au pays sélectionné. Vous pourrez le modifier plus tard.",
  "transfer.phoneLabel": "Numéro de téléphone",
  "transfer.phonePlaceholder": "6 12 34 56 78",
  "transfer.phoneContinue": "Continuer",
  "transfer.phoneConfirmed": "Numéro validé",
  "receiveMethod.mobileMoney": "Mobile Money",
  "receiveMethod.bank": "Compte bancaire",
  "country.cm": "Cameroun",
  "country.cd": "République démocratique du Congo",
  "country.cg": "République du Congo",
  "country.gh": "Ghana",
  "country.ng": "Nigeria",
  "country.cm.pitchTitle": "Votre crypto en FCFA, directement sur votre Mobile Money.",
  "country.cm.pitchSubtitle": "Convertissez vos USDT, USDC et autres actifs pris en charge en XAF et recevez votre argent sur votre moyen de paiement local.",
  "country.gh.pitchTitle": "Transformez votre crypto en cedis.",
  "country.gh.pitchSubtitle": "Convertissez votre crypto en cedis ghanéens et recevez-la via votre moyen de paiement local.",
  "country.ng.pitchTitle": "De la crypto au naira. Sans complications.",
  "country.ng.pitchSubtitle": "Convertissez vos actifs numériques pris en charge en NGN et recevez votre argent via les moyens de paiement locaux disponibles.",
  "country.za.pitchTitle": "Votre crypto convertie en rand, sur votre compte bancaire.",
  "country.za.pitchSubtitle": "Convertissez vos actifs numériques en rand sud-africain et recevez votre argent via les rails bancaires locaux pris en charge.",
  "transfer.nonCustodial": "Transfert non dépositaire",
  "transfer.title": "Préparez votre envoi",
  "transfer.explainer": "Choisissez l’actif et le montant. Votre wallet affiche ensuite la destination et les frais avant toute confirmation.",
  "transfer.sender": "Wallet émetteur",
  "transfer.notConnected": "Non connecté",
  "transfer.openingWallet": "Ouverture du wallet…",
  "transfer.connect": "Connecter avec WalletConnect",
  "transfer.assetSent": "Actif envoyé",
  "transfer.ethereumNetwork": "Ethereum Mainnet",
  "transfer.bitcoinNetwork": "Bitcoin Mainnet",
  "transfer.bitcoinPreviewBadge": "Parcours Bitcoin en préparation",
  "transfer.bitcoinPreviewTitle": "BTC reste sur le réseau Bitcoin.",
  "transfer.bitcoinPreviewText": "Le parcours BTC natif est visible dans cette preview. L’envoi sera activé lorsqu’une adresse de réception Bitcoin et un connecteur compatible seront configurés.",
  "transfer.amount": "Montant",
  "transfer.cashback": "Cashback estimé",
  "transfer.preparing": "Préparation serveur…",
  "transfer.confirmWallet": "Confirmez dans votre wallet…",
  "transfer.retry": "Réessayer dans mon wallet",
  "transfer.submit": "Vérifier dans mon wallet",
  "transfer.receipt": "Résumé avant confirmation",
  "transfer.network": "Réseau",
  "transfer.asset": "Actif",
  "transfer.destination": "Réception",
  "transfer.inWallet": "Affichée avant la signature",
  "transfer.request": "Demande",
  "transfer.networkFees": "Frais réseau",
  "transfer.feesInWallet": "Estimés et affichés avant confirmation",
  "transfer.confirmed": "Transaction confirmée",
  "transfer.failed": "Transaction échouée",
  "transfer.sent": "Transaction envoyée",
  "transfer.etherscan": "Voir sur Etherscan",
  "transfer.new": "Nouvel envoi",
  "error.rejected": "La demande a été refusée dans le wallet.",
  "error.insufficient": "Solde insuffisant pour le montant et les frais réseau.",
  "error.invalidAmount": "Saisissez un montant positif valide.",
  "error.service": "Le service de préparation est momentanément indisponible.",
  "error.transaction": "La transaction n’a pas pu être préparée ou envoyée.",
  "country.nl": "Pays-Bas",
  "country.gb": "Royaume-Uni",
  "country.sn": "Sénégal",
  "country.ci": "Côte d’Ivoire",
  "country.za": "Afrique du Sud",
  "footer.brandText": "Concept statique d’une expérience de carte centrée sur le wallet. Cette démo locale n’est ni un émetteur, ni un service de paiement, ni un produit officiel de Trust Wallet.",
  "footer.product": "Produit",
  "footer.features": "Fonctionnalités",
  "footer.rewards": "Récompenses",
  "footer.premium": "Carte Premium",
  "footer.faq": "FAQ",
  "footer.legal": "Légal",
  "footer.privacy": "Avis de confidentialité",
  "footer.terms": "Conditions",
  "footer.cookies": "Cookies",
  "footer.aml": "Politique AML",
  "footer.support": "Support",
  "footer.help": "Centre d’aide",
  "footer.contact": "Contact",
  "footer.status": "Page de statut",
  "footer.security": "Sécurité",
  "footer.legalText": "© 2026 Démo de concept statique. Ce prototype ne revendique aucune affiliation, licence, émission de carte, récompense, réseau d’acceptation ou statut réglementaire. La valeur des cryptomonnaies peut fluctuer fortement. Ne partagez jamais une phrase de récupération ou une clé privée avec un site web.",
} as const;

export type TranslationKey = keyof typeof fr;

const en: Record<TranslationKey, string> = {
  "header.realTransactions": "Real transactions",
  "header.realValue": "Real value",
  "header.getStarted": "Get started",
  "home.mainnetAvailable": "Crypto → local currency",
  "home.heroTitle": "Digital money,",
  "home.heroAccent": "finally local.",
  "home.heroLead": "Turn your crypto and stablecoins into local currency and receive your money directly through the payment method you use every day.",
  "home.heroAssets": "ETH, BTC, USDT, USDC and other supported assets → XAF, NGN, GHS, ZAR and other local currencies.",
  "home.sendNow": "Convert now",
  "home.nonCustodial": "Amount shown upfront",
  "home.lockedAddress": "Mobile Money or bank",
  "home.etherscanReceipt": "Your usual wallet",
  "home.walletPreview": "Animated wallet connection preview",
  "home.preview": "PREVIEW",
  "home.secureRequest": "Final amount shown before confirmation",
  "home.localSignature": "You confirm",
  "home.previewSendLabel": "You send",
  "home.previewSendValue": "100 USDT",
  "home.previewReceiveLabel": "You receive",
  "home.previewReceiveValue": "≈ 59,800 XAF",
  "home.previewCountryLabel": "Country",
  "home.previewCountryValue": "Cameroon",
  "home.previewMethodLabel": "Receive via",
  "home.previewMethodValue": "MTN Mobile Money",
  "home.walletsTitle": "Your usual wallet is all you need to start",
  "home.walletsNote": "Connection via WalletConnect. Final compatibility depends on your wallet and network settings.",
  "home.countriesKicker": "Available in these Mobile Money countries",
  "home.countriesNote": "The list of countries and receiving methods will expand progressively.",
  "home.verifiable": "Three steps. No complicated journey.",
  "home.simple": "As simple as",
  "home.clear": "a transfer.",
  "home.visibleDetails": "Connect your wallet, choose your local currency, then receive funds through an option available in your country.",
  "feature.keys.title": "Connect your wallet",
  "feature.keys.text": "Select your wallet or provide the address you want to send your assets from.",
  "feature.destination.title": "Choose your currency",
  "feature.destination.text": "Select your country and the currency you want to receive your money in.",
  "feature.proof.title": "Receive locally",
  "feature.proof.text": "We convert and send the funds to the payment method available in your country.",
  "home.oneNetwork": "Supported assets",
  "home.twoAssets": "The assets",
  "home.clearJourney": "you already use.",
  "home.networkText": "Send ETH, USDC and USDT on Ethereum Mainnet. The native BTC journey is shown separately so the network is explicit before confirmation.",
  "home.prepareTransaction": "Choose what to convert",
  "home.nativeAsset": "You send",
  "home.cryptoAssetsLabel": "Crypto & stablecoins",
  "home.cryptoAssetsList": "ETH · BTC · USDT · USDC",
  "home.chainBadgeTop": "CRYPTO",
  "home.chainBadgeBottom": "LOCAL",
  "home.officialContract": "You receive",
  "home.localCurrenciesLabel": "Local currencies",
  "home.localCurrenciesList": "XAF · NGN · GHS · ZAR",
  "home.securityFirst": "Your money deserves transparency",
  "home.verify": "See everything.",
  "home.thenSign": "Before you confirm.",
  "home.securityText": "The amount sent, applied rate, fees and final amount received stay visible. No surprises when you confirm.",
  "home.chainCheck": "Amount sent and asset",
  "home.feeEstimate": "Applied rate and fees",
  "home.explicitConfirmation": "Final amount and receiving method",
  "home.conversionRequest": "Conversion preview",
  "home.serverReady": "READY TO REVIEW",
  "home.yourRequest": "Your conversion",
  "home.requestDetails": "Asset + amount + local currency",
  "home.fullAddress": "Final amount visible",
  "home.youConfirm": "You confirm",
  "home.ready": "Ready to start?",
  "home.yourWallet": "Your money is digital.",
  "home.yourSignature": "Your daily life does not",
  "home.yourTransaction": "always have to be.",
  "home.openTransfer": "Get started",
  "home.risk": "Asset, currency and payment-method availability depends on your country and the services supported.",
  "transactions.title": "Choose.",
  "transactions.accent": "Review. Confirm.",
  "transactions.lead": "Choose BTC, ETH, USDT or USDC. Ligne shows the network before your wallet presents the destination and fees.",
  "transactions.localSignature": "Local signature",
  "transactions.workspace": "Mainnet transfer",
  "transactions.back": "Back to home",
  "wallet.label": "Your wallet",
  "wallet.connected": "Mainnet connected",
  "wallet.secure": "Secure connection",
  "wallet.balanceUnavailable": "Balance unavailable",
  "wallet.loading": "Loading…",
  "wallet.mainnetBalance": "Mainnet balance",
  "wallet.recognized": "Address recognized. Now choose the asset and amount to send.",
  "wallet.testConversion": "Prepare my transfer",
  "wallet.disconnect": "Disconnect",
  "wallet.connectTitle": "Connect your wallet",
  "wallet.scan": "Use your usual wallet to get started.",
  "wallet.opening": "Opening QR code…",
  "wallet.open": "Open WalletConnect",
  "wallet.notConfigured": "WalletConnect is not configured on this version.",
  "wallet.cancelled": "WalletConnect was cancelled or interrupted. Open the QR code and approve the connection in your wallet.",
  "transfer.countryPromptTitle": "Where would you like to receive your money?",
  "transfer.countryPromptSubtitle": "Select your country to see the available currencies and receiving methods.",
  "transfer.countryPromptHint": "Choose a country to continue.",
  "transfer.genericPitchTitle": "Your crypto, received locally.",
  "transfer.genericPitchSubtitle": "Convert your supported assets and receive your money through the receiving method available in your country.",
  "transfer.phonePromptTitle": "Which number should receive your funds?",
  "transfer.phonePromptSubtitle": "This dialing code matches the selected country. You can change it later.",
  "transfer.phoneLabel": "Phone number",
  "transfer.phonePlaceholder": "6 12 34 56 78",
  "transfer.phoneContinue": "Continue",
  "transfer.phoneConfirmed": "Number verified",
  "receiveMethod.mobileMoney": "Mobile Money",
  "receiveMethod.bank": "Bank account",
  "country.cm": "Cameroon",
  "country.cd": "DR Congo",
  "country.cg": "Republic of Congo",
  "country.gh": "Ghana",
  "country.ng": "Nigeria",
  "country.cm.pitchTitle": "Your crypto in FCFA, straight to your Mobile Money.",
  "country.cm.pitchSubtitle": "Convert your USDT, USDC and other supported assets into XAF and receive your money through your local payment method.",
  "country.gh.pitchTitle": "Turn your crypto into cedis.",
  "country.gh.pitchSubtitle": "Convert crypto into Ghana cedis and receive it through your local payment method.",
  "country.ng.pitchTitle": "From crypto to naira. Without the hassle.",
  "country.ng.pitchSubtitle": "Convert supported digital assets into NGN and receive your money through available local payment rails.",
  "country.za.pitchTitle": "Your crypto converted into rand, straight to your bank account.",
  "country.za.pitchSubtitle": "Convert your digital assets into South African rand and receive your money through supported local banking rails.",
  "transfer.nonCustodial": "Non-custodial transfer",
  "transfer.title": "Prepare your transfer",
  "transfer.explainer": "Choose the asset and amount. Your wallet then displays the destination and fees before any confirmation.",
  "transfer.sender": "Sender wallet",
  "transfer.notConnected": "Not connected",
  "transfer.openingWallet": "Opening wallet…",
  "transfer.connect": "Connect with WalletConnect",
  "transfer.assetSent": "Asset sent",
  "transfer.ethereumNetwork": "Ethereum Mainnet",
  "transfer.bitcoinNetwork": "Bitcoin Mainnet",
  "transfer.bitcoinPreviewBadge": "Bitcoin flow in preparation",
  "transfer.bitcoinPreviewTitle": "BTC stays on the Bitcoin network.",
  "transfer.bitcoinPreviewText": "The native BTC journey is visible in this preview. Sending will be enabled once a Bitcoin receiving address and a compatible connector are configured.",
  "transfer.amount": "Amount",
  "transfer.cashback": "Estimated cashback",
  "transfer.preparing": "Preparing on server…",
  "transfer.confirmWallet": "Confirm in your wallet…",
  "transfer.retry": "Try again in my wallet",
  "transfer.submit": "Review in my wallet",
  "transfer.receipt": "Summary before confirmation",
  "transfer.network": "Network",
  "transfer.asset": "Asset",
  "transfer.destination": "Recipient",
  "transfer.inWallet": "Displayed before signing",
  "transfer.request": "Request",
  "transfer.networkFees": "Network fees",
  "transfer.feesInWallet": "Estimated and displayed before confirmation",
  "transfer.confirmed": "Transaction confirmed",
  "transfer.failed": "Transaction failed",
  "transfer.sent": "Transaction sent",
  "transfer.etherscan": "View on Etherscan",
  "transfer.new": "New transfer",
  "error.rejected": "The request was rejected in your wallet.",
  "error.insufficient": "Insufficient balance for the amount and network fees.",
  "error.invalidAmount": "Enter a valid positive amount.",
  "error.service": "The preparation service is temporarily unavailable.",
  "error.transaction": "The transaction could not be prepared or sent.",
  "country.nl": "Netherlands",
  "country.gb": "United Kingdom",
  "country.sn": "Senegal",
  "country.ci": "Ivory Coast",
  "country.za": "South Africa",
  "footer.brandText": "Static concept for a wallet-first card experience. This local demo is not an issuer, payment service, or official Trust Wallet product.",
  "footer.product": "Product",
  "footer.features": "Features",
  "footer.rewards": "Rewards",
  "footer.premium": "Premium Card",
  "footer.faq": "FAQ",
  "footer.legal": "Legal",
  "footer.privacy": "Privacy notice",
  "footer.terms": "Terms",
  "footer.cookies": "Cookies",
  "footer.aml": "AML Policy",
  "footer.support": "Support",
  "footer.help": "Help Center",
  "footer.contact": "Contact",
  "footer.status": "Status Page",
  "footer.security": "Security",
  "footer.legalText": "© 2026 Static concept demo. No affiliation, licensing, card issuance, rewards, acceptance network or regulatory status is asserted by this prototype. Cryptocurrency values can fluctuate significantly. Never share a recovery phrase or private key with any website.",
};

type LanguageContextValue = {
  language: Language;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("fr");

  useEffect(() => {
    const detectLanguage = () => {
      const detected: Language = navigator.languages.some((item) => item.toLowerCase().startsWith("fr")) ? "fr" : "en";
      setLanguageState(detected);
    };

    detectLanguage();
    window.addEventListener("languagechange", detectLanguage);
    return () => window.removeEventListener("languagechange", detectLanguage);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    t(key) {
      return language === "fr" ? fr[key] : en[key];
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
